### ISSUE TITLE
Renaming sublayers?

### ISSUE THREAD

**Issue by chammell85** [seblavoie/adobe-illustrator-layer-renamer#4]
Hello, thats a really great script which I often use for renaming my layers. The only problem is that the script only rename toplayer. I there a possibility to rename the sublayers?

**Comment by seblavoie** [comment]
Thanks, I am glad the script is helpful to your process :) You are right that it only works with top-level layers. As far as I know, sublayers are not easily manageable via scripting in illustrator. What you could do is temporarily move the sublayers to top-level layers, rename, and then move them back where they were. It’s not a perfect solution, but it should work.
